apiVersion: apps/v1
kind: Deployment
metadata:
  name: sccstore-ui
  labels:
    app: sccstore-ui
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: sccstore
    app.openshift.io/runtime: spring-boot
  annotations:
    helm-revision: "{{ .Release.Revision }}"
    timestamp: {{ now | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sccstore-ui
  template:
    metadata:
      labels:
        app: sccstore-ui
    spec:
      containers:
      - name: sccstore-ui
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "K8S"
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            configMapKeyRef:
              name: sccstore-ui-spring-config
              key: k8s-config.json
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: "/certs/"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8778
            scheme: HTTPS
          timeoutSeconds: 4
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8778
              scheme: HTTPS
            timeoutSeconds: 4
            initialDelaySeconds: 30
            periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "700m"
          limits:
            memory: "300Mi"
            cpu: "2000m"
      volumes:
      - name: certs
        secret:
          secretName: sccstore-webcert
      serviceAccountName: default
#      imagePullSecrets:
      #- name: regcred
#      - name: default-dockercfg-b2zgj
