apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sccstore-ui-route
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough 
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  to:
    kind: Service
    name: sccstore-ui-service
    weight: 100