apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sccstore-ui-route
  #app.kubernetes.io/managed-by: helm
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: 8443
  tls:
    termination: passthrough 
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  to:
    kind: Service
    name: sccstore-ui-service
    weight: 100