apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
  labels:
    app: postgres
    app.kubernetes.io/part-of: sccstore
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          {{- if eq .Values.storage.persistent "true" }}
          persistentVolumeClaim:
            claimName: pg-pvc
          {{- else }}
            emptyDir: {}
          {{- end }}
{{- if eq .Values.storage.persistent "true" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
{{- end }}