apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi