apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sccstore-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: dockerconfig-ws
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/domenico-piol/SCCstore
        - name: revision
          value: domenico
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_IMAGE
          value: quay.io/quarkus/ubi-quarkus-native-s2i:22.1-java11
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -B
            - package
            - '-DskipTests'
            - '-Dnative'
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: buildah-ui-container
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: ui
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-ui:$(context.taskRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: buildah-qcomplaints-container
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: qcomplaints
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-qcomplaints:$(context.taskRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: buildah-pcomplaints-container
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: pcomplaints
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-pcomplaints:$(context.taskRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
#    - name: list-dir
#      taskRef:
#        name: list-directory
#      runAfter:
#        - fetch-repository
#      params:
#        - name: sub-dirs
#          value:
#            - .
#      workspaces:
#        - name: directory
#          workspace: dockerconfig-ws
