apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sccstore-pipeline
spec:
  description: | 
    This pipeline builds the SCCStore application
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: repo-branch
      type: string
      description: The branch to be used.
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: dockerconfig-ws
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-branch)
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_IMAGE
          value: quay.io/quarkus/ubi-quarkus-native-s2i:22.2-java17
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -B
            - package
            - '-DskipTests'
            - '-Dnative'
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: ui-buildah
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: ui
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-ui:$(context.pipelineRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: ui-skopeo-copy
      taskRef:
        name: skopeo-copy
      runAfter:
        - ui-buildah
      params:
        - name: srcImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-ui:$(context.pipelineRun.uid)
        - name: destImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-ui:latest
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      workspaces:
        - name: images-url
          workspace: shared-workspace
    - name: qcomplaints-buildah
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: qcomplaints
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-qcomplaints:$(context.pipelineRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: qcomplaints-skopeo-copy
      taskRef:
        name: skopeo-copy
      runAfter:
        - qcomplaints-buildah
      params:
        - name: srcImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-qcomplaints:$(context.pipelineRun.uid)
        - name: destImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-qcomplaints:latest
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      workspaces:
        - name: images-url
          workspace: shared-workspace
    - name: pcomplaints-buildah
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: pcomplaints
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-pcomplaints:$(context.pipelineRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: pcomplaints-skopeo-copy
      taskRef:
        name: skopeo-copy
      runAfter:
        - pcomplaints-buildah
      params:
        - name: srcImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-pcomplaints:$(context.pipelineRun.uid)
        - name: destImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-pcomplaints:latest
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      workspaces:
        - name: images-url
          workspace: shared-workspace
    - name: liquibase-buildah
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: liquibase
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/sccstore-liquibase:$(context.pipelineRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: liquibase-skopeo-copy
      taskRef:
        name: skopeo-copy
      runAfter:
        - liquibase-buildah
      params:
        - name: srcImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-liquibase:$(context.pipelineRun.uid)
        - name: destImageURL
          value: docker://registry-1.docker.io/domenicopiol/sccstore-liquibase:latest
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      workspaces:
        - name: images-url
          workspace: shared-workspace
#
# CAN BE USED FOR DEBUGGING
#    - name: list-dir
#      taskRef:
#        name: list-directory
#      runAfter:
#        - fetch-repository
#      params:
#        - name: sub-dirs
#          value:
#            - .
#      workspaces:
#        - name: directory
#          workspace: dockerconfig-ws
