apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sccstore-serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "10s"
    spec:
      containers:
      - image: registry-1.docker.io/domenicopiol/sccstore-serverless:latest
        env:
        - name: SCC_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sccstore-serverless-config
              key: SCC_DB_HOST