all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /pg-host/pg-prod.pem
    ansible_host_key_checking: false
  children:
    pg-databases:
      hosts:
        ec2-18-218-152-152.us-east-2.compute.amazonaws.com:
          ansible_host: 18.218.152.152