apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: postgres
data:
  #POSTGRES_DB: sccstore
  #POSTGRES_USER: sccstore
  #POSTGRES_PASSWORD: sccstore
  POSTGRESQL_USER: sccstore
  POSTGRESQL_PASSWORD: sccstore
  POSTGRESQL_DATABASE: sccstore