kind: Service
apiVersion: v1
metadata:
  name: pg-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
