apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-ansible-playbook
data:
  playbook.yaml: |
{{  .Files.Get "playbooks/playbook.yaml" | indent 4 }}
  hosts.yaml: |
{{  .Files.Get "playbooks/hosts.yaml" | indent 4 }}