apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sccstore-pcomplaints
  labels:
    app.kubernetes.io/part-of: sccstore
    app.openshift.io/runtime: python
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "6s"
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        env:
        - name: SCC_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sccstore-pcomplaints-config
              key: SCC_DB_HOST