kind: Service
apiVersion: v1
metadata:
  name: sccstore-pcomplaints-service
  labels:
    app.kubernetes.io/part-of: sccstore
    app.openshift.io/runtime: python
spec:
  type: ClusterIP
  selector:
    app: sccstore-pcomplaints
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sccstore-pcomplaints
  labels:
    app.kubernetes.io/part-of: sccstore
    app.openshift.io/runtime: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sccstore-pcomplaints
  template:
    metadata:
      labels:
        app: sccstore-pcomplaints
    spec:
      containers:
      - name: sccstore-pcomplaints
        image: registry-1.docker.io/domenicopiol/sccstore-pcomplaints:latest
        imagePullPolicy: Always
        env:
          - name: PORT 
            value: "8080"
          - name: SCC_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: sccstore-pcomplaints-config
                key: SCC_DB_HOST
          - name: SCC_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: sccstore-pcomplaints-config
                key: SCC_DB_NAME