# Default values for sccstore-pcomplaints.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry-1.docker.io/domenicopiol
  name: sccstore-pcomplaints
  tag: latest
