certDir: ${user.dir}/../../certs/
spring:
  profiles:
    active: LOCAL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: sccstore
    key-store: file:${certDir}/sccstore-ui-certificate.p12
  error:
    path: /error
management:
  health:
    probes:
      enabled: true
  server:
    port: 8778
    ssl:
      enabled: true
      key-store-type: PKCS12
      key-store-password: sccstore
      key-store: file:${certDir}/sccstore-ui-certificate.p12
---
spring:
  config:
    activate:
      on-profile: K8S
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://win10-magnificent-roundworm:5432/sccstore
    username: sccstore
    password: sccstore
server:
  ssl:
    key-store-password: sccstore
    key-store: file:/certs/webcert.p12
management:
  server:
    ssl:
      key-store-password: sccstore
      key-store: file:/certs/webcert.p12
---
spring:
  config:
    activate:
      on-profile: LOCAL
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sccstore
    username: sccstore
    password: sccstore