spring:
  profiles:
    active: LOCAL
server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: sccstore
    key-store: file:/Users/domenico/Documents/Projects/certs/sccstore-ui-certificate.p12
  error:
    path: /error
management:
  health:
    probes:
      enabled: true
  server:
    port: 8443
    ssl:
      enabled: true
      key-store-type: PKCS12
      key-store-password: sccstore
      key-store: file:/Users/domenico/Documents/Projects/certs/sccstore-ui-certificate.p12
---
spring:
    config:
        activate:
            on-profile: K8S
server:
  ssl:
    key-store-password: sccstore
    key-store: file:/certs/webcert.p12
management:
  server:
    ssl:
      key-store-password: sccstore
      key-store: file:/certs/webcert.p12
---
spring:
    config:
        activate:
            on-profile: LOCAL