sccstore:
  certDir: ${user.dir}/../../certs/
  platform: postgres
  url: jdbc:postgresql://win10-postgresql:5432/sccstore
  username: sccstore
  password: sccstore
spring:
  application:
    name: sccstore-ui
  profiles:
    active: LOCAL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: sccstore
    key-store: file:${sccstore.certDir}/sccstore-ui-certificate.p12
  error:
    path: /error
management:
  health:
    probes:
      enabled: true
  server:
    port: 8778
    ssl:
      enabled: true
      key-store-type: PKCS12
      key-store-password: sccstore
      key-store: file:${sccstore.certDir}/sccstore-ui-certificate.p12
---
spring:
  config:
    activate:
      on-profile: K8S
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    platform: ${sccstore.platform}
    url: ${sccstore.url}
    username: ${sccstore.username}
    password: ${sccstore.password}
server:
  ssl:
    key-store-password: sccstore
    key-store: file:/certs/webcert.p12
management:
  server:
    ssl:
      key-store-password: sccstore
      key-store: file:/certs/webcert.p12
---
spring:
  config:
    activate:
      on-profile: LOCAL
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false 
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sccstore
    username: sccstore
    password: sccstore