# Default values for sccstore-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  stage: dev
  database: 
    service: ec2-18-189-24-210.us-east-2.compute.amazonaws.com
    dbName: psccstore
  namespaces:
    nsfront: sccstore-front
    nsservice: sccstore-service
    nsdb: sccstore-db
ui:
  enabled: false
  image:
    #repository: registry-1.docker.io/domenicopiol
    repository: registry-1.docker.io/rhworkshops
    tag: latest
pcomplaints:
  enabled: false
  image:
    repository: registry-1.docker.io/rhworkshops
    tag: latest
qcomplaints:
  enabled: false
  image:
    repository: registry-1.docker.io/rhworkshops
    tag: latest
database:
  enabled: false
  storage:
    storageClass: gp3
ansible:
  enabled: true
  setupInfrastructure: true
  image:
    repository: registry-1.docker.io/rhworkshops
    tag: latest