apiVersion: v1
kind: Service
metadata:
  name: fedora-test-service
spec:
  selector:
    vm.kubevirt.io/name: fedora-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
      nodePort: 31022
