name: CI for SCCstore

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Project 
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -Dnative --file pom.xml
    
    # for docker build see https://docs.docker.com/ci-cd/github-actions/
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push - UI
      id: docker_build_ui
      uses: docker/build-push-action@v2
      with:
        context: ./ui/
        file: ./ui/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-ui:latest,${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-ui:${{ github.sha }} 

    - name: Image digest - UI
      run: echo ${{ steps.docker_build_ui.outputs.digest }}

    - name: Build and push - PCOMPLAINTS
      id: docker_build_pcomplaints
      uses: docker/build-push-action@v2
      with:
        context: ./pcomplaints/
        file: ./pcomplaints/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-pcomplaints:latest,${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-pcomplaints:${{ github.sha }} 

    - name: Image digest - PCOMPLAINTS
      run: echo ${{ steps.docker_build_pcomplaints.outputs.digest }}

    - name: Build and push - QCOMPLAINTS
      id: docker_build_qcomplaints
      uses: docker/build-push-action@v2
      with:
        context: ./qcomplaints/
        file: ./qcomplaints/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-qcomplaints:latest,${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-qcomplaints:${{ github.sha }} 

    - name: Image digest - QCOMPLAINTS
      run: echo ${{ steps.docker_build_qcomplaints.outputs.digest }}