name: CI for SCCstore

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Project 
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    # for docker build see https://docs.docker.com/ci-cd/github-actions/
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push - UI
      id: docker_build_ui
      uses: docker/build-push-action@v2
      with:
        context: ./ui/
        file: ./ui/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-ui:latest,${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-ui:${{ github.sha }} 

    - name: Image digest - UI
      run: echo ${{ steps.docker_build_ui.outputs.digest }}

    - name: Build and push - SERVERLESS
      id: docker_build_serverless
      uses: docker/build-push-action@v2
      with:
        context: ./serverless/
        file: ./serverless/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-serverless:latest,${{ secrets.DOCKER_HUB_USERNAME }}/sccstore-serverless:${{ github.sha }} 

    - name: Image digest - SERVERLESS
      run: echo ${{ steps.docker_build_serverless.outputs.digest }}